### ISSUE TITLE
Not compatible with k8s 1.25+

### ISSUE THREAD

**Issue by msuterski** [TwiN/k8s-ttl-controller#57]
### Describe the bug

It looks like the controller is using k8s API that were removed in k8s 1.25.

I was wondering if you're planning to release updated version to support more recent k8s APIs.

### What do you see?

Errors about accessing k8s APIs removed in version 1.25

### What do you expect to see?

I'd like the controller to be compatible with k8s API 1.25+

### List the steps that must be taken to reproduce this issue

Deploy the controller to k8s 1.25 and up

### Version

latest

### Additional information

thanks for providing this useful tool!

**Comment by TwiN** [comment]
🤔 I currently have the application deployed in a cluster running 1.25.
Can you provide any logs that show the error the application is running into?

**Comment by msuterski** [comment]
I was wrong here. I'm sorry about it.

When upgrading k8s versions, the GKE console displays APIs used and clients using them that are not compatible with the next version. 

The ttl-conroller was showing up on this list as something using APIs removed in 1.25.

We've upgraded since then and it seem to be functioning correctly. I'm assuming the client matches the API it uses based on the k8s version it's running on. 

Thank you for looking into it

**Comment by TwiN** [comment]
@msuterski No worries!
