### ISSUE TITLE
Delete after update

### ISSUE THREAD

**Issue by hiddenmarten** [TwiN/k8s-ttl-controller#96]
### Describe the feature request

I propose adding an additional annotation, such as `k8s-ttl-controller.twin.sh/updateTimestamp`. The purpose of this annotation is straightforward: it serves as an alternative to `metadata.creationTimestamp` for cases where a user wants to control the object's deletion timing based on a redeployment, rather than delaying deletion after the initial creation.

The logic is straightforward: if the annotation exists, it is used as the starting point. If not, `metadata.creationTimestamp` is used by default.

### Why do you personally want this feature to be implemented?

This feature would be helpful for my project. I'm happy to contribute to its implementation. I think it would be nice to discuss the details of this functionality beforehand.

**Comment by TwiN** [comment]
Something like `k8s-ttl-controller.twin.sh/refreshed-at` would be a great idea, I agree, and your suggested implementation (check annotation first then fallback to `metadata.creationTimestamp` makes sense!

**Comment by TwiN** [comment]
Implemented by #97
