### ISSUE TITLE
Incorrect log message using `refresh-at` annotation

### ISSUE THREAD

**Issue by hiddenmarten** [TwiN/k8s-ttl-controller#98]
### Describe the bug

Using `refresh-at` annotation I've got in the logs wrong calculations of expiration time.

### What do you see?

```
2024/12/09 14:21:34 [namespaces/namespace-oak] is configured with a TTL of 10m, which means it will expire in -26m8s
2024/12/09 14:22:23 Execution took 77989ms, sleeping for 5m0s
2024/12/09 14:27:48 [namespaces/namespace-oak] is configured with a TTL of 10m, which means it has expired 3m5s ago
2024/12/09 14:27:48 [namespaces/namespace-oak] deleted
```

### What do you expect to see?

I expect to see correct calculations.

### Version

current master branch

### Additional information

I'll deal with that myself. :)

**Comment by TwiN** [comment]
Fixed by #101
